library(shiny)

script_path <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(script_path)
getwd()
list.files("App-1")

#runApp("App-1")
#runExample("02_text")
#runExample("03_reactivity")
#runExample("04_mpg")   
#runExample("05_sliders")
runExample("06_tabsets")  
#runExample("07_widgets")  
#runExample("08_html")
#runExample("09_upload") 
#runExample("10_download")
#runExample("11_timer")  
